[package]
name = "phar"
version = "0.0.0"
authors = ["SOFe <sofe2038@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
repository = "https://github.com/SOF3/phar"
homepage = "https://github.com/SOF3/phar"
readme = "README.md"
description = "Rust library for PHP phar format"

[dependencies]
bitflags = "1.2.1"
byteorder = "1.3.4"
cfg-if = "0.1.10"
derive_builder = "0.9.0"
itertools = "0.9.0"
snafu = "0.6.6"
tempfile = {version = "3.1.0", optional = true}

[features]
default = ["temp-buffer"]
temp-buffer = ["tempfile"]
