name: Pages
on:
  push:
    branches: [master]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: pages
          token: ${{secrets.GH_TOKEN}}
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          default: true
      - run: cargo install wasm-pack
      - run: npm install
        working-directory: web
      - run: npm run build
        working-directory: web
      - run: cargo doc --features docsrs
      - run: rm -r pages/*
      - run: cp -r target/doc pages/api
      - run: cp -r web/dist/* pages
      - run: git add .
        working-directory: pages
      - run: git -c user.name=github-actions[bot] -c user.email=41898282+github-actions[bot]@users.noreply.github.com commit -m "Update for ${{github.sha}}"
        working-directory: pages
      - run: git push
        working-directory: pages
